apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map
data:
  kafka-url: kafka-service:9092
  user-server-url: http://backend-user-service:8080/user
  product-server-url: http://backend-product-service:8081/product
  auth-server-url: http://backend-auth-service:8082/auth
  cart-server-url: http://backend-cart-service:8083/cart
  like-server-url: http://backend-like-service:8084/like
  order-server-url: http://backend-order-service:8085/order
  backend-url: http://api-gateway-service:3002
  mongodb-uri: mongodb://mongodb-service:27017
