name: validate k8s files
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: validate kubernetes config files
        id: k8s
        uses: yakketyyak/validate-k8s-files@master
        with:
          files: file1,dir1,dir2,file2
          report_name: My final report
      - uses: actions/upload-artifact@main
        with:
          name: ${{ steps.k8s.outputs.report }}
          path: ${{ steps.k8s.outputs.report }}
